---
- name: update the packages
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: add nexus groupname
  group:
    name: "{{nexus_group}}"

- name: add nexus username
  user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    home: /usr/share/nexus
    createhome: yes

- name: create nexus directory
  file:
    path: "{{ nexus_dir }}"
    state: directory
    mode: "0755"

- name: create sonatype nexus directory
  file:
    path: "{{ sona_type_dir }}"
    state: directory
    mode: "0755"

# download nexus package
- name: download the nexus packages
  unarchive:
    src: "{{ nexus_url }}"
    dest: "{{ nexus_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: uncomment the run as user fron nexus file
  lineinfile:
    path: "{{ nexus_rc_file }}"
    regexp: 'run_as_user="nexus"'
    line: run_as_user="nexus"

- name: change the ownership of file
  file:
    path: "{{ nexus_dir }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    mode: "0755"
    recurse: yes
    state: directory

- name: change the ownership of file
  file:
    path: "{{ sona_type_dir }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    mode: "0755"
    recurse: yes
    state: directory

- name: create symbolic links to /etc/init.d/nexus
  file:
    src: "{{ nexus_service_loc }}"
    dest: /etc/init.d/nexus
    state: link
    force: yes

- name: configure runlevel links for nexus
  command: update-rc.d nexus defaults
  notify:
    - start nexus service

